# -*- coding: utf-8 -*-
"""AI Sustainability shopping assistant

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sz-Gp1d2Srdgsn6Zi_HW_iuYJQlrlQCK

Data Loading
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
import joblib

import pandas as pd

amazon = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/amazon_products_sales_data_cleaned.csv")

hm = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/handm.csv")

carbon = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/personal_carbon_footprint_behavior.csv")


print(amazon.head())
print(hm.head())
print(carbon.head())

"""Sustainability Score Generation"""

import numpy as np

amazon['product_rating'] = amazon['product_rating'].fillna(0)

amazon['discount_percentage'] = amazon['discount_percentage'].fillna(0)

amazon['sustainability_tags'] = amazon['sustainability_tags'].fillna('None')

amazon['sustainability_score'] = (amazon['product_rating'] * 15)

amazon.loc[amazon['sustainability_tags']!= 'None','sustainability_score'] += 25

amazon['sustainability_score'] += (amazon['discount_percentage']* 0.2)

amazon['sustainability_score'] = (amazon['sustainability_score'].clip(0,100))

"""H&M Sustainability Analysis"""

hm['recycled'] = hm['materials'].str.contains('Recycled',case=False,na=False)

hm['sustainability_score'] = (hm['recycled'].apply(lambda x: 90 if x else 50))

"""H&M Sustainability Analysis"""

def recommend_products( category):

    products = amazon[amazon['product_category'] == category]

    products = products.sort_values(by='sustainability_score',ascending=False)

    return products[['product_title','sustainability_score']].head(5)

print(recommend_products( "Phones" ))

"""User Carbon Footprint Analysis"""

avg_carbon = carbon['carbon_footprint_kg'].mean()

print("Average Carbon Footprint:",avg_carbon)

"""train_model.py"""

import pandas as pd
import joblib

from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestRegressor

amazon = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/amazon_products_sales_data_cleaned.csv")

amazon['product_rating'] = (amazon['product_rating'].fillna(0))

amazon['total_reviews'] = (amazon['total_reviews'].fillna(0))

amazon['purchased_last_month'] = (amazon['purchased_last_month'].fillna(0))

amazon['discount_percentage'] = (amazon['discount_percentage'].fillna(0))

amazon['sustainability_tags'] = (amazon['sustainability_tags'].fillna('None'))

amazon['sustainability_score'] = (amazon['product_rating']*15)

amazon.loc[amazon['sustainability_tags']!='None','sustainability_score']+=25

X = amazon[['product_rating','total_reviews','purchased_last_month','discount_percentage']]

y = amazon['sustainability_score']

X_train,X_test,y_train,y_test = (train_test_split(X,y,test_size=0.2,random_state=42))

model = RandomForestRegressor()

model.fit(X_train,y_train)

joblib.dump(model,"sustainability_model.pkl")

"""Prediction"""

import joblib

model = joblib.load("sustainability_model.pkl")

prediction = model.predict([[4.5,2000,500,20]])
print("Predicted Score:",prediction[0])

"""Streamlit App"""

import joblib

model = joblib.load("sustainability_model.pkl")

# Example values
rating = 4.5
reviews = 2000
purchases = 500
discount = 25

score = model.predict([
    [
        rating,
        reviews,
        purchases,
        discount
    ]
])[0]

print(f"Sustainability Score: {score:.2f}")

if score > 80:
    print("Highly Sustainable Product")
elif score > 60:
    print("Moderately Sustainable Product")
else:
    print("Low Sustainability Product")